### ISSUE TITLE
注入失败？

### ISSUE THREAD

**Issue by xyhzds** [ElytraServers/Overpowered#1]
![image](https://github.com/user-attachments/assets/df1da140-1b2f-4327-a8f9-4289f252c570)
https://mclo.gs/XPHlYew

**Comment by xyhzds** [comment]
是和哪个mod不兼容吗

**Comment by Taskeren** [comment]
啊，OP的问题

**Comment by fbjh** [comment]
作者，我也注入失败了，期待下个版本修复

**Comment by Taskeren** [comment]
看一下 [v1.0.2](https://github.com/ElytraServers/Overpowered/releases/tag/v1.0.2)，在我这边的 261 环境下是可以用的。如果还有问题的话请再把这个 issue 打开，并且附上日志。

**Comment by xyhzds** [comment]
> 看一下 [v1.0.2](https://github.com/ElytraServers/Overpowered/releases/tag/v1.0.2)，在我这边的 261 环境下是可以用的。如果还有问题的话请再把这个 issue 打开，并且附上日志。

ok了，可以正常启动
