### ISSUE TITLE
 上维领域超因果单元 不被 虚空采矿场III 认为是能源仓

### ISSUE THREAD

**Issue by MikuMiddo** [ElytraServers/Overpowered#4]
安装 上维领域超因果单元 至 虚空采矿场III后提示结构不完整
![image](https://github.com/user-attachments/assets/804fd595-57a8-48cc-98bf-29164eea40de)

![image](https://github.com/user-attachments/assets/57b57c4e-44af-45a8-8eac-2ff32b480470)

**Comment by MikuMiddo** [comment]
将同位置换为能源仓后可以正常运行 其他结构不存在问题

**Comment by Taskeren** [comment]
因为创造能源仓是 *动态* 调整电压，所以在放下来的时候被视为最低电压等级，无法满足虚空采矿场的电压等级必须高于采矿场等级的要求。

你可以先调整能源仓电压到合适的等级，再放置机器控制器。

这个要求同时被所有 `GT_MetaTileEntity_DrillerBase` 子类机器共享，所以其他钻机类的机器也都可能遇到这个问题。
